/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techtest_nativefactorial_MainActivity */

#ifndef _Included_com_techtest_nativefactorial_MainActivity
#define _Included_com_techtest_nativefactorial_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techtest_nativefactorial_MainActivity
 * Method:    calculateFactorial
 * Signature: (I)I
 */
JNIEXPORT jdouble JNICALL Java_com_techtest_nativefactorial_MainActivity_calculateFactorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
